### ISSUE TITLE
Custom row hover background color with frozen column

### ISSUE THREAD

**Issue by greggailly** [Autodesk/react-base-table#194]
[![Edit Alternate rows](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/alternate-rows-x43em?fontsize=14&hidenavigation=1&theme=dark)

Hi !

First of all thanks for the great work !

Small issue we have been having:
We like to "alternate" the rows background colors to give a striped effect. 
We achieve this with a custom classed assigned with the "rowClassName" attribute. That same class has a :hover selector to give a small color change on hover.
However the hover effect does not spread to the frozen columns when hovering on the "main" table.
The hover effect works fine if there are no frozen columns.

Is there any workaround to this issue ?

Thanks in advance !

**Comment by nihgwu** [comment]
for table with frozen columns, the frozen cells are in another table, so you have to do something like the following:
```css
.BaseTable__row:hover, .BaseTable__row--hovered {
  background-color: #f3f3f3;
}
```

so for your demo, you have to use `.special-row.BaseTable__row--hovered`

for striped effect, I think you can use `rowProps = ({ rowIndex }) => ({ 'data-odd': rowIndex % 2 === 1 })` and 
```css
.BaseTable__row[data-odd="true"]:hover, .BaseTable__row--hovered[data-odd="true"] {
  background-color: #f3f3f3;
}
```
